// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Transport.Messages
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public enum ClientMessageContent : byte
{
  NONE = 0,
  LoginMessage
};

public enum ServerMessageContent : byte
{
  NONE = 0,
  DespawnMessage = 12,
  PlayerInfoMessage = 24,
  PlayerOwnershipMessage = 25,
  PlayerSpawnedMessage = 26,
  RangeInitMessage = 27,
  SpawnMessage = 35,
};

public struct ClientMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_11_23(); }
  public static ClientMessage GetRootAsClientMessage(ByteBuffer _bb) { return GetRootAsClientMessage(_bb, new ClientMessage()); }
  public static ClientMessage GetRootAsClientMessage(ByteBuffer _bb, ClientMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClientMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long ServerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public Transport.Messages.ClientMessageContent MessageType { get { int o = __p.__offset(6); return o != 0 ? (Transport.Messages.ClientMessageContent)__p.bb.Get(o + __p.bb_pos) : Transport.Messages.ClientMessageContent.NONE; } }
  public TTable? Message<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(8); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public Transport.Messages.LoginMessage MessageAsLoginMessage() { return Message<Transport.Messages.LoginMessage>().Value; }

  public static Offset<Transport.Messages.ClientMessage> CreateClientMessage(FlatBufferBuilder builder,
      long server_id = 0,
      Transport.Messages.ClientMessageContent message_type = Transport.Messages.ClientMessageContent.NONE,
      int messageOffset = 0) {
    builder.StartTable(3);
    ClientMessage.AddServerId(builder, server_id);
    ClientMessage.AddMessage(builder, messageOffset);
    ClientMessage.AddMessageType(builder, message_type);
    return ClientMessage.EndClientMessage(builder);
  }

  public static void StartClientMessage(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddServerId(FlatBufferBuilder builder, long serverId) { builder.AddLong(0, serverId, 0); }
  public static void AddMessageType(FlatBufferBuilder builder, Transport.Messages.ClientMessageContent messageType) { builder.AddByte(1, (byte)messageType, 0); }
  public static void AddMessage(FlatBufferBuilder builder, int messageOffset) { builder.AddOffset(2, messageOffset, 0); }
  public static Offset<Transport.Messages.ClientMessage> EndClientMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Transport.Messages.ClientMessage>(o);
  }
}

public struct ServerMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_11_23(); }
  public static ServerMessage GetRootAsServerMessage(ByteBuffer _bb) { return GetRootAsServerMessage(_bb, new ServerMessage()); }
  public static ServerMessage GetRootAsServerMessage(ByteBuffer _bb, ServerMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long ServerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public Transport.Messages.ServerMessageContent MessageType { get { int o = __p.__offset(6); return o != 0 ? (Transport.Messages.ServerMessageContent)__p.bb.Get(o + __p.bb_pos) : Transport.Messages.ServerMessageContent.NONE; } }
  public TTable? Message<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(8); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public Transport.Messages.DespawnMessage MessageAsDespawnMessage() { return Message<Transport.Messages.DespawnMessage>().Value; }
  public Transport.Messages.PlayerInfoMessage MessageAsPlayerInfoMessage() { return Message<Transport.Messages.PlayerInfoMessage>().Value; }
  public Transport.Messages.PlayerOwnershipMessage MessageAsPlayerOwnershipMessage() { return Message<Transport.Messages.PlayerOwnershipMessage>().Value; }
  public Transport.Messages.PlayerSpawnedMessage MessageAsPlayerSpawnedMessage() { return Message<Transport.Messages.PlayerSpawnedMessage>().Value; }
  public Transport.Messages.SpawnMessage MessageAsSpawnMessage() { return Message<Transport.Messages.SpawnMessage>().Value; }

  public static Offset<Transport.Messages.ServerMessage> CreateServerMessage(FlatBufferBuilder builder,
      long server_id = 0,
      Transport.Messages.ServerMessageContent message_type = Transport.Messages.ServerMessageContent.NONE,
      int messageOffset = 0) {
    builder.StartTable(3);
    ServerMessage.AddServerId(builder, server_id);
    ServerMessage.AddMessage(builder, messageOffset);
    ServerMessage.AddMessageType(builder, message_type);
    return ServerMessage.EndServerMessage(builder);
  }

  public static void StartServerMessage(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddServerId(FlatBufferBuilder builder, long serverId) { builder.AddLong(0, serverId, 0); }
  public static void AddMessageType(FlatBufferBuilder builder, Transport.Messages.ServerMessageContent messageType) { builder.AddByte(1, (byte)messageType, 0); }
  public static void AddMessage(FlatBufferBuilder builder, int messageOffset) { builder.AddOffset(2, messageOffset, 0); }
  public static Offset<Transport.Messages.ServerMessage> EndServerMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Transport.Messages.ServerMessage>(o);
  }
  public static void FinishServerMessageBuffer(FlatBufferBuilder builder, Offset<Transport.Messages.ServerMessage> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedServerMessageBuffer(FlatBufferBuilder builder, Offset<Transport.Messages.ServerMessage> offset) { builder.FinishSizePrefixed(offset.Value); }
}

public struct SpawnMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_11_23(); }
  public static SpawnMessage GetRootAsSpawnMessage(ByteBuffer _bb) { return GetRootAsSpawnMessage(_bb, new SpawnMessage()); }
  public static SpawnMessage GetRootAsSpawnMessage(ByteBuffer _bb, SpawnMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SpawnMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long ServerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string PrefabId { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPrefabIdBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetPrefabIdBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetPrefabIdArray() { return __p.__vector_as_array<byte>(6); }
  public Transport.Messages.TVector3? Position { get { int o = __p.__offset(8); return o != 0 ? (Transport.Messages.TVector3?)(new Transport.Messages.TVector3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Transport.Messages.TQuaternion? Rotation { get { int o = __p.__offset(10); return o != 0 ? (Transport.Messages.TQuaternion?)(new Transport.Messages.TQuaternion()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartSpawnMessage(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddServerId(FlatBufferBuilder builder, long serverId) { builder.AddLong(0, serverId, 0); }
  public static void AddPrefabId(FlatBufferBuilder builder, StringOffset prefabIdOffset) { builder.AddOffset(1, prefabIdOffset.Value, 0); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<Transport.Messages.TVector3> positionOffset) { builder.AddStruct(2, positionOffset.Value, 0); }
  public static void AddRotation(FlatBufferBuilder builder, Offset<Transport.Messages.TQuaternion> rotationOffset) { builder.AddStruct(3, rotationOffset.Value, 0); }
  public static Offset<Transport.Messages.SpawnMessage> EndSpawnMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Transport.Messages.SpawnMessage>(o);
  }
}

public struct DespawnMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_11_23(); }
  public static DespawnMessage GetRootAsDespawnMessage(ByteBuffer _bb) { return GetRootAsDespawnMessage(_bb, new DespawnMessage()); }
  public static DespawnMessage GetRootAsDespawnMessage(ByteBuffer _bb, DespawnMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DespawnMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long ServerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Transport.Messages.DespawnMessage> CreateDespawnMessage(FlatBufferBuilder builder,
      long server_id = 0) {
    builder.StartTable(1);
    DespawnMessage.AddServerId(builder, server_id);
    return DespawnMessage.EndDespawnMessage(builder);
  }

  public static void StartDespawnMessage(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddServerId(FlatBufferBuilder builder, long serverId) { builder.AddLong(0, serverId, 0); }
  public static Offset<Transport.Messages.DespawnMessage> EndDespawnMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Transport.Messages.DespawnMessage>(o);
  }
}

public struct LoginMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_11_23(); }
  public static LoginMessage GetRootAsLoginMessage(ByteBuffer _bb) { return GetRootAsLoginMessage(_bb, new LoginMessage()); }
  public static LoginMessage GetRootAsLoginMessage(ByteBuffer _bb, LoginMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LoginMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string SessionToken { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSessionTokenBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetSessionTokenBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetSessionTokenArray() { return __p.__vector_as_array<byte>(4); }
  public long CharacterId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Transport.Messages.LoginMessage> CreateLoginMessage(FlatBufferBuilder builder,
      StringOffset session_tokenOffset = default(StringOffset),
      long character_id = 0) {
    builder.StartTable(2);
    LoginMessage.AddCharacterId(builder, character_id);
    LoginMessage.AddSessionToken(builder, session_tokenOffset);
    return LoginMessage.EndLoginMessage(builder);
  }

  public static void StartLoginMessage(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSessionToken(FlatBufferBuilder builder, StringOffset sessionTokenOffset) { builder.AddOffset(0, sessionTokenOffset.Value, 0); }
  public static void AddCharacterId(FlatBufferBuilder builder, long characterId) { builder.AddLong(1, characterId, 0); }
  public static Offset<Transport.Messages.LoginMessage> EndLoginMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Transport.Messages.LoginMessage>(o);
  }
}

public struct PlayerInfoMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_11_23(); }
  public static PlayerInfoMessage GetRootAsPlayerInfoMessage(ByteBuffer _bb) { return GetRootAsPlayerInfoMessage(_bb, new PlayerInfoMessage()); }
  public static PlayerInfoMessage GetRootAsPlayerInfoMessage(ByteBuffer _bb, PlayerInfoMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerInfoMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long PlayerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Transport.Messages.PlayerInfoMessage> CreatePlayerInfoMessage(FlatBufferBuilder builder,
      long player_id = 0) {
    builder.StartTable(1);
    PlayerInfoMessage.AddPlayerId(builder, player_id);
    return PlayerInfoMessage.EndPlayerInfoMessage(builder);
  }

  public static void StartPlayerInfoMessage(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPlayerId(FlatBufferBuilder builder, long playerId) { builder.AddLong(0, playerId, 0); }
  public static Offset<Transport.Messages.PlayerInfoMessage> EndPlayerInfoMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Transport.Messages.PlayerInfoMessage>(o);
  }
}

public struct PlayerOwnershipMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_11_23(); }
  public static PlayerOwnershipMessage GetRootAsPlayerOwnershipMessage(ByteBuffer _bb) { return GetRootAsPlayerOwnershipMessage(_bb, new PlayerOwnershipMessage()); }
  public static PlayerOwnershipMessage GetRootAsPlayerOwnershipMessage(ByteBuffer _bb, PlayerOwnershipMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerOwnershipMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long PlayerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Transport.Messages.PlayerOwnershipMessage> CreatePlayerOwnershipMessage(FlatBufferBuilder builder,
      long player_id = 0) {
    builder.StartTable(1);
    PlayerOwnershipMessage.AddPlayerId(builder, player_id);
    return PlayerOwnershipMessage.EndPlayerOwnershipMessage(builder);
  }

  public static void StartPlayerOwnershipMessage(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPlayerId(FlatBufferBuilder builder, long playerId) { builder.AddLong(0, playerId, 0); }
  public static Offset<Transport.Messages.PlayerOwnershipMessage> EndPlayerOwnershipMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Transport.Messages.PlayerOwnershipMessage>(o);
  }
}

public struct PlayerSpawnedMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_11_23(); }
  public static PlayerSpawnedMessage GetRootAsPlayerSpawnedMessage(ByteBuffer _bb) { return GetRootAsPlayerSpawnedMessage(_bb, new PlayerSpawnedMessage()); }
  public static PlayerSpawnedMessage GetRootAsPlayerSpawnedMessage(ByteBuffer _bb, PlayerSpawnedMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerSpawnedMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long ServerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long InventoryServerId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long EquipmentServerId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Transport.Messages.PlayerSpawnedMessage> CreatePlayerSpawnedMessage(FlatBufferBuilder builder,
      long server_id = 0,
      long inventory_server_id = 0,
      long equipment_server_id = 0) {
    builder.StartTable(3);
    PlayerSpawnedMessage.AddEquipmentServerId(builder, equipment_server_id);
    PlayerSpawnedMessage.AddInventoryServerId(builder, inventory_server_id);
    PlayerSpawnedMessage.AddServerId(builder, server_id);
    return PlayerSpawnedMessage.EndPlayerSpawnedMessage(builder);
  }

  public static void StartPlayerSpawnedMessage(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddServerId(FlatBufferBuilder builder, long serverId) { builder.AddLong(0, serverId, 0); }
  public static void AddInventoryServerId(FlatBufferBuilder builder, long inventoryServerId) { builder.AddLong(1, inventoryServerId, 0); }
  public static void AddEquipmentServerId(FlatBufferBuilder builder, long equipmentServerId) { builder.AddLong(2, equipmentServerId, 0); }
  public static Offset<Transport.Messages.PlayerSpawnedMessage> EndPlayerSpawnedMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Transport.Messages.PlayerSpawnedMessage>(o);
  }
}


}
